---
name: 💻 CLI Build

on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - name: 🔵 Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x

      - uses: pre-commit/action@v3.0.1

  build:
    name: 💻 CLI Build
    runs-on: ubuntu-latest
    needs:
      - lint

    strategy:
      matrix:
        arch:
          - amd64
          - arm64

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🔵 Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x

      - name: ⏬ Install Dependencies
        run: go get .

      - name: 🧪 Test
        run: go test -v ./...

      - name: 👷‍♂️ Build for ${{ matrix.arch }}
        run: GOOS=linux GOARCH=${{ matrix.arch }} go build -o ws-cli-${{ matrix.arch }}
